# Generated by Django 5.1.5 on 2025-01-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.PositiveSmallIntegerField(help_text='Grado del ciclo universitario, por ejemplo, 1')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del ciclo.')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del ciclo.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ciclo está activo.')),
            ],
        ),
    ]
