# Generated by Django 5.1.5 on 2025-01-17 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del curso, por ejemplo, 'Matemáticas Avanzadas'.", max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del curso.')),
                ('creditos', models.PositiveSmallIntegerField(help_text='Número de créditos del curso.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el curso.')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Letra del aula.', max_length=2)),
                ('capacidad', models.PositiveIntegerField(help_text='Capacidad máxima de estudiantes en el aula.')),
                ('ciclo', models.ForeignKey(help_text='Ciclo al que pertenece esta aula.', on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='ciclos.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='CursoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(help_text="Horario del curso en el aula, por ejemplo, 'Lunes 8:00-10:00'.", max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se asignó el curso al aula.')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_aulas', to='aulas.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_aulas', to='aulas.curso')),
            ],
        ),
    ]
