# Generated by Django 5.1.5 on 2025-01-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_remove_cursoaula_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoaula',
            name='duracion',
            field=models.IntegerField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
