# Generated by Django 5.1.5 on 2025-01-17 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_cursoaula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoaula',
            name='duracion',
            field=models.DecimalField(decimal_places=1, help_text='Duración del curso en horas', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
