# Generated by Django 5.1.5 on 2025-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_alter_cursoaula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoaula',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Hora de fin de este curso', max_length=100, null=True),
        ),
    ]
