# Generated by Django 5.1.5 on 2025-01-18 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_alter_cursoaula_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoaula',
            name='dia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
    ]
