# Generated by Django 5.1.5 on 2025-01-17 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del estudiante.', max_length=150)),
                ('apellido', models.CharField(max_length=50)),
                ('codigo', models.CharField(help_text='Codigo del estudiante.', max_length=8, unique=True)),
                ('carrera', models.CharField(help_text='Carrera universitaria que cursa el estudiante.', max_length=50)),
                ('correo', models.EmailField(help_text='Correo electrónico institucional del estudiante.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('edad', models.PositiveSmallIntegerField(help_text='Edad del estudiante. Debe estar entre 16 y 99 años.', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(99)])),
                ('fecha_registro', models.DateTimeField(help_text='Fecha en la que se registró el estudiante.')),
                ('aula', models.ForeignKey(blank=True, help_text='Aula asignada al estudiante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='aulas.aula')),
                ('ciclo', models.ForeignKey(help_text='Ciclo universitario del estudiante.', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='ciclos.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del estudiante.', max_length=150)),
                ('apellido', models.CharField(max_length=50)),
                ('titulo', models.CharField(help_text="Título académico, por ejemplo, 'Dr.', 'Mtro.', 'Ing.', etc.", max_length=100)),
                ('correo', models.EmailField(help_text='Correo electrónico institucional del estudiante.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('fecha_registro', models.DateTimeField(help_text='Fecha en la que se registró el estudiante.')),
                ('cursos', models.ManyToManyField(related_name='profesores', to='aulas.curso')),
            ],
        ),
    ]
