# Generated by Django 5.1.5 on 2025-01-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_registro',
        ),
    ]
